apiVersion: v1
kind: Service
metadata:
  name: nginx-argocd-svc
  namespace: dev
  
spec:
  selector:
    app: dev
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
